apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metrics-demo
  template:
    metadata:
      labels:
        app: metrics-demo
    spec:
      containers:
        - name: metrics-demo
          image: k8s.gcr.io/hpa-example
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 500m
          ports:
            - containerPort: 80
